### ISSUE TITLE
"Unexpected EOF error" in line 171 of neogeo.sh

### ISSUE THREAD

**Issue by d3viant** [funkycochise/Insert-Coin#2]
Hey, love your work. Running your update_all_insertcoin.sh script after your recent edit of neogeo.sh results in two error messages:

./folders/neogeo.sh: line 171: unexpected EOF while looking for matching  `''
./folders/neogeo.sh: : line 189: syntax error: unexpected end of file

At first I suspected sd card corruption, but I checked your repo and saw the change is new, and I tried replacing my neogeo.sh with a fresh copy of yours, same error. Tried to fix it - I figured it was unescaped characters and attempted to fix it myself - but couldn't figure out how to fix the EOF error without adding a double-quotation mark that had no business being there at the end of the file lol. So I figured that's what this is for. :)

**Comment by funkycochise** [comment]
Hi, thank you for the head up.
I will fix it quickly.

**Comment by funkycochise** [comment]
I pushed the corrections : you can update_all then update_all_insertcoin
