### ISSUE TITLE
IremM92 Turbo

### ISSUE THREAD

**Issue by wickerwaka** [funkycochise/Insert-Coin#2]
The IremM92_Turbo rbf is out of date and should be removed. It seems like it is causing people to get mismatched MRAs and rbf files, because they get the latest MRAs from the main distribution but the rbf from insert coin is being used.

**Comment by funkycochise** [comment]
Hi martin, I couldn't really see why it could cause any problem as the core has another name IremM92_Turbo
with its own list of dedicated folder and mras in _alternatives.
_Undercover Cops (Turbo)
_Superior Soldiers (Turbo)
_R-Type Leo (Turbo)
_Ninja Baseball Bat Man (Turbo)
_Mystic Riders (Turbo)
_Major Title 2 (Turbo)
_Lethal Thunder (Turbo)
_In The Hunt (Turbo)
_Hook (Turbo)
_Gunforce - Battle Fire Engulfed Terror Island (Turbo)
_Gun Force II (Turbo)
_Dream Soccer '94 (Turbo)
_Blade Master (Turbo)
no other M92 core is downloaded, so there shouldn't be any mismatch,
regular versions are being provided by update_all.
anyway I don't want you to be upset against me, if you don't want to see this version distributed anymore.
so I will see what I can do.

**Comment by wickerwaka** [comment]
I think it is because MiSTer strips anything after a `_` when looking for an rbf, in order to ignore the dates in the filenames. So `IremM92_Turbo` in the mra will find the right rbf, but `IremM92` could also find the turbo version, depending on what order they appear in the filesystem.

Not upset, but the turbo functionality is now included in the latest version of the core along with some other improvements, so there probably isn't a need to maintain this separate version any more.

**Comment by funkycochise** [comment]
you're right, the core name isn't different enough. it was always the turbo one that was used.
I remove the turbo core and went for specific mra/config instead. I changed the setname as I wanted to keep separated turbo mras and avoid mismatch.
I spoke to hempknight and thank him for highlighting the issue.
Thank you for your work and sorry for having bothered you with this problem.
Pierre.

**Comment by funkycochise** [comment]
got rid of turbo specific core.
